version: '3.3'

services:
  spring:
    container_name: credit-app
    image: credit-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  angular:
      container_name: angular-docker-container
      build: ./angular-client-app/
      ports:
        - '9000:80'
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=credit_app


